name: Deploy to Vercel

on:
  push:
    branches:
      - main  # или другая ветка, если вы используете другую

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to Vercel
      env:
        VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
        VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      run: |
        curl -fsSL https://vercel.com/download -o vercel-cli.tar.gz
        tar -xvzf vercel-cli.tar.gz
        ./vercel --token $VERCEL_TOKEN --prod
